# test with:
#   go run ./cmd/helm template example example://does-not-matter/example
apiVersion: v1
type: download
name: example-download
version: 0.1.0
config:
  downloaders:
  - command: run.sh
    protocols:
      - example
