# run with
#   go run ./cmd/helm cli1 foo bar --baz=qux quxx
#
# example: combine with getter plugin
#  go run ./cmd/helm template example example://does-not-matter/example --post-renderer postr1
apiVersion: v1
type: postrender/v1
name: example-postrender
version: 0.1.0
runtimeConfig:
  platformCommand:
    - command: ${HELM_PLUGIN_DIR}/run.sh
