# test with:
#   go run ./cmd/helm template example example://does-not-matter/example
name: example-legacy-download
version: 0.1.0
description: example download plugin type
downloaders:
- command: run.sh
  protocols:
    - example-legacy
